import 'emoji-mart/dist-es/vendor/raf-polyfill';
export declare class Picker {
    constructor();
    host: HTMLElement;
    EMOJI_DATASOURCE_VERSION: string;
    _forceUpdate: boolean;
    _loadedCategories: any[];
    recent: any;
    include: any;
    exclude: any;
    onEmojiClicked: any;
    emojiSize: number;
    perLine: number;
    i18n: any;
    pickerStyle: any;
    width: string;
    emoji: string;
    color: string;
    set: string;
    skin: any;
    native: any;
    sheetSize: any;
    backgroundImageFn: any;
    emojisToShowFilter: any;
    showPreview: boolean;
    showAnchors: boolean;
    emojiTooltip: any;
    autoFocus: boolean;
    custom: any;
    title: string;
    _i18n: any;
    _categories: any[];
    _hideRecent: any;
    _firstRender: boolean;
    _firstRenderTimeout: any;
    _leaveTimeout: any;
    _hasStickyPosition: any;
    _preview: any;
    _categoryRefs: any;
    _scroll: any;
    _waitingForPaint: any;
    _scrollTop: any;
    _clientHeight: any;
    _scrollHeight: any;
    _search: any;
    _anchors: any;
    _allCategoriesLoaded: boolean;
    _firstCategoryIndex: number;
    _lastCategoryIndex: number;
    _loadOffset: number;
    _isLoading: boolean;
    clearSearch(): void;
    resetScroll(): void;
    componentWillLoad(): void;
    componentDidLoad(): void;
    loadMore(): void;
    categoryLoaded(categoryIndex: number, emojisCount: number): void;
    componentDidUpdate(): void;
    componentDidUnload(): void;
    testStickyPosition(): void;
    handleEmojiOver(emoji: any): void;
    handleEmojiLeave(): void;
    handleEmojiClick(emoji: any, e: any): void;
    handleScroll(): void;
    handleScrollPaint(): void;
    getAllCategoryComponents(): NodeListOf<HTMLEmartCategoryElement>;
    handleSearch(emojis: any): void;
    forceUpdate(): void;
    handleAnchorClick(category: any, i: any): void;
    handleSkinChange(skin: any): void;
    updateCategoriesSize(): void;
    setAnchorsRef(c: any): void;
    setSearchRef(c: any): void;
    setPreviewRef(c: any): void;
    setScrollRef(c: any): void;
    render(): JSX.Element;
}
