/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  Category as EmartCategory
} from './components/category/category';

declare global {
  interface HTMLEmartCategoryElement extends EmartCategory, HTMLElement {
  }
  var HTMLEmartCategoryElement: {
    prototype: HTMLEmartCategoryElement;
    new (): HTMLEmartCategoryElement;
  };
  interface HTMLElementTagNameMap {
    "emart-category": HTMLEmartCategoryElement;
  }
  interface ElementTagNameMap {
    "emart-category": HTMLEmartCategoryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "emart-category": JSXElements.EmartCategoryAttributes;
    }
  }
  namespace JSXElements {
    export interface EmartCategoryAttributes extends HTMLAttributes {
      categoryId?: any;
      categoryKey?: any;
      custom?: any;
      emojiProps?: any;
      emojis?: any;
      hasStickyPosition?: boolean;
      i18n?: any;
      name?: string;
      native?: boolean;
      perLine?: number;
      recent?: string[];
    }
  }
}

