/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  Search as EmartSearch
} from './components/search/search';

declare global {
  interface HTMLEmartSearchElement extends EmartSearch, HTMLElement {
  }
  var HTMLEmartSearchElement: {
    prototype: HTMLEmartSearchElement;
    new (): HTMLEmartSearchElement;
  };
  interface HTMLElementTagNameMap {
    "emart-search": HTMLEmartSearchElement;
  }
  interface ElementTagNameMap {
    "emart-search": HTMLEmartSearchElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "emart-search": JSXElements.EmartSearchAttributes;
    }
  }
  namespace JSXElements {
    export interface EmartSearchAttributes extends HTMLAttributes {
      autoFocus?: boolean;
      custom?: any;
      emojisToShowFilter?: any;
      exclude?: any;
      i18n?: any;
      include?: any;
      maxResults?: number;
      onSearch?: any;
    }
  }
}

